import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

import ThemeSwitch from '@/components/ThemeSwitch';
import AccountPreview from '@/components/AccountPreview';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen`}>
        {/* Top Bar */}
        <div className="flex items-center justify-between h-14 shrink-0 px-4 py-2 bg-gray-100 dark:bg-gray-800 border-b-2 border-gray-200 dark:border-gray-700">
          <div>
            <h3 className="h-8 text-lg text-accent dark:text-accent-dark font-bold">CloudFileManager</h3>
          </div>

          {/* Theme Switch */}
          <div className="text-red-600">
            <ThemeSwitch />
          </div>

          {/* Account Icon and Username */}
          <div className="flex items-center space-x-2">
            <AccountPreview />
          </div>
        </div>

        {/* Children pages */}
        {children}
      </body>
    </html>
  );
}
