# Generated by Django 4.2.6 on 2024-01-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
    ]
